'use client';

import { LoaderCircle, Search, SlidersHorizontal, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Place } from '@/types/place';
import { normalizePlace, PlaceDetailSheet } from './PlaceDetailSheet';
import { PlaceCard } from './PlaceCard';

export function PlaceSearch({ onAddToDay }: { onAddToDay: (place: Place) => void }) {
  const [query, setQuery] = useState(''); const [places, setPlaces] = useState<Place[]>([]); const [suggestions, setSuggestions] = useState<Array<{ placeId: string; name: string; secondaryText?: string }>>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [configured, setConfigured] = useState(true); const [savedIds, setSavedIds] = useState<string[]>([]); const [selected, setSelected] = useState<Place | null>(null);
  useEffect(() => { const trimmed = query.trim(); if (!trimmed) { setSuggestions([]); return; } const timer = window.setTimeout(() => { const controller = new AbortController(); fetch(`/api/places/autocomplete?q=${encodeURIComponent(trimmed)}`, { signal: controller.signal }).then(async (response) => { const data = await response.json(); setConfigured(data.configured !== false); return data; }).then((data) => setSuggestions(data.suggestions ?? [])).catch((reason) => { if (reason.name !== 'AbortError') setSuggestions([]); }); return () => controller.abort(); }, 300); return () => window.clearTimeout(timer); }, [query]);
  useEffect(() => { const trimmed = query.trim(); if (!trimmed) { setPlaces([]); setError(''); return; } const timer = window.setTimeout(() => { const controller = new AbortController(); setLoading(true); setError(''); fetch(`/api/places/search?q=${encodeURIComponent(trimmed)}`, { signal: controller.signal }).then(async (response) => { const data = await response.json(); setConfigured(data.configured !== false); if (!response.ok && data.configured !== false) throw new Error(data.message ?? 'Search failed'); return data; }).then((data) => setPlaces((data.places ?? []).map(normalizePlace))).catch((reason) => { if (reason.name !== 'AbortError') { setPlaces([]); setError(reason instanceof Error ? reason.message : 'Search is unavailable right now. Please try again.'); } }).finally(() => setLoading(false)); return () => controller.abort(); }, 300); return () => window.clearTimeout(timer); }, [query]);
  return <div className="food-search"><div className="food-search-bar"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search restaurants, cafés or bakeries..." aria-label="Search restaurants, cafés or bakeries" />{query ? <button onClick={() => { setQuery(''); setSuggestions([]); }} aria-label="Clear search"><X size={16} /></button> : <SlidersHorizontal size={16} />}</div>{suggestions.length > 0 && <div className="place-suggestions">{suggestions.slice(0, 5).map((suggestion) => <button key={suggestion.placeId} onClick={() => { setQuery(suggestion.name); setSuggestions([]); }}><Search size={14} /><span><strong>{suggestion.name}</strong><small>{suggestion.secondaryText}</small></span></button>)}</div>}{loading && <div className="food-search-status"><LoaderCircle className="animate-spin" size={18} /> Searching real places…</div>}{!loading && !query && <div className="food-search-empty"><Search size={25} /><h2>Find your next table</h2><p>Search real restaurants, cafés and bakeries in Japan.</p>{!configured && <span>Foursquare Places is not configured yet. Add <code>NEXT_PUBLIC_FOURSQUARE_API_KEY</code> to enable search.</span>}</div>}{!loading && query && error && <div className="food-search-empty error"><h2>Search unavailable</h2><p>{error}</p></div>}{!loading && query && !error && places.length === 0 && <div className="food-search-empty"><h2>No places found</h2><p>Try a different restaurant, café or bakery.</p>{!configured && <span>Add <code>NEXT_PUBLIC_FOURSQUARE_API_KEY</code> to enable Foursquare search.</span>}</div>}<div className="place-results">{places.map((place) => <PlaceCard key={place.placeId} place={place} saved={savedIds.includes(place.placeId)} onSave={() => setSavedIds((ids) => ids.includes(place.placeId) ? ids.filter((id) => id !== place.placeId) : [...ids, place.placeId])} onOpen={() => setSelected(place)} onAddToDay={() => onAddToDay(place)} />)}</div><PlaceDetailSheet place={selected} onClose={() => setSelected(null)} /></div>;
}
